const EMOJI_SIZE = 50;
const EMOJI_PANE_PADDING_VERTICAL = 0;
const EMOJI_PANE_PADDING_HORIZONTAL = 10;
const EMOJI_PANE_PADDING = 10;
const EMOJI_PANE_HEIGHT =  EMOJI_SIZE + EMOJI_PANE_PADDING_VERTICAL*2;

export { EMOJI_PANE_HEIGHT, EMOJI_SIZE }